---
- name: Configure repositories
  include_tasks: repositories.yml

- name: Install default packages
  include_tasks: packages.yml

- name: Remove subscription nag
  include_tasks: subscription-nag.yml
