---
- name: Configure repositories
  ansible.builtin.include_tasks: repositories.yml
- name: Install default packages
  ansible.builtin.include_tasks: packages.yml
- name: Remove subscription nag
  ansible.builtin.include_tasks: subscription-nag.yml
