---
- name: Restart NUT services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
    enabled: true
  loop:
    - nut-server
    - nut-monitor
  when: nut_mode == 'server'

- name: Restart NUT client services
  ansible.builtin.systemd:
    name: nut-monitor
    state: restarted
    enabled: true
  when: nut_mode == 'client'
