---
- name: Reload netdata claiming
  command: /usr/sbin/netdatacli reload-claiming-state
  failed_when: false  # May fail if service not fully started yet

- name: Clean up netdata-repo package
  file:
    path: /tmp/netdata-repo.deb
    state: absent
