apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cephfs
provisioner: cephfs.csi.ceph.com
parameters:
  clusterID: 9626d083-bbd2-431c-886a-d5b428239a78
  fsName: cephfs
  pool: cephfs_data
  
  # Using v1 protocol (port 6789) - more compatible
  monitors: "10.150.10.41:6789,10.150.10.42:6789,10.150.10.43:6789,10.150.10.44:6789,10.150.10.45:6789,10.150.10.46:6789"
  
  csi.storage.k8s.io/provisioner-secret-name: csi-cephfs-secret
  csi.storage.k8s.io/provisioner-secret-namespace: ceph-csi-cephfs
  csi.storage.k8s.io/controller-expand-secret-name: csi-cephfs-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: ceph-csi-cephfs
  csi.storage.k8s.io/node-stage-secret-name: csi-cephfs-secret
  csi.storage.k8s.io/node-stage-secret-namespace: ceph-csi-cephfs

reclaimPolicy: Delete
allowVolumeExpansion: true
