---
- name: Check if Tailscale is authenticated
  command: tailscale status
  register: tailscale_status
  failed_when: false
  changed_when: false

- name: Authenticate Tailscale
  command: tailscale up --authkey={{ tailscale_auth_key }}
  when: tailscale_status.rc != 0
  register: auth_status
  no_log: true

- name: Check if Tailscale SSH is already enabled
  shell: tailscale status --json | jq -r '.Self.CapMap | has("https://tailscale.com/cap/ssh")'
  register: ssh_check
  changed_when: false
  failed_when: false
  when: tailscale_enable_ssh | default(true)

- name: Enable Tailscale SSH
  command: tailscale set --ssh
  when:
    - tailscale_enable_ssh | default(true)
    - ssh_check.stdout != "true"
  register: ssh_result
