---
- name: Include installation tasks
  ansible.builtin.include_tasks: install.yml
- name: Include authentication tasks
  ansible.builtin.include_tasks: auth.yml
- name: Include certificate tasks
  ansible.builtin.include_tasks: certs.yml
  when: tailscale_setup_proxmox_certs | default(false)
