[nut_server]
pve004 ansible_host=10.150.10.44

[nut_netclients]
pve001 ansible_host=10.150.10.41
pve002 ansible_host=10.150.10.42
pve003 ansible_host=10.150.10.43
pve005 ansible_host=10.150.10.45
pve006 ansible_host=10.150.10.46
pve007 ansible_host=10.150.10.47

[proxmox:children]
nut_server
nut_netclients

[proxmox:vars]
ansible_user=root
netdata_claim_token={{ vault_netdata_claim_token }}
netdata_claim_rooms={{ vault_netdata_proxmox_claim_rooms }}

[k3s_master]
k3s-master-01 ansible_host=10.150.10.163

[k3s_workers]
k3s-worker-01 ansible_host=10.150.10.164
k3s-worker-02 ansible_host=10.150.10.165
k3s-worker-03 ansible_host=10.150.10.166

[k3s_cluster:children]
k3s_master
k3s_workers

[k3s_cluster:vars]
netdata_claim_token={{ vault_netdata_claim_token }}
netdata_claim_rooms={{ vault_netdata_k3s_claim_rooms }}

[all:vars]
ansible_user=adambehn
ansible_ssh_private_key_file=~/.ssh/id_ed25519_behner
ansible_python_interpreter=/usr/bin/python3
netdata_claim_token={{ vault_netdata_claim_token }}
netdata_claim_rooms={{ vault_netdata_default_claim_rooms }}
